import { GameStage } from "@/types/game";

export type Language = "en" | "ar";

export const isArabic = (language: Language) => language === "ar";

export const t = (language: Language, value: Record<Language, string>) => value[language];

export const stageLabels: Record<Language, Record<GameStage, string>> = {
  en: {
    onboarding: "Welcome",
    learning: "Learning Phase",
    short_term: "Short-Term Memory",
    reordering: "Reordering Task",
    puzzle: "Puzzle Stage",
    long_term: "Long-Term Memory",
    results: "Results",
  },
  ar: {
    onboarding: "الترحيب",
    learning: "مرحلة التعلّم",
    short_term: "الذاكرة قصيرة المدى",
    reordering: "مهمة الترتيب",
    puzzle: "مرحلة اللغز",
    long_term: "الذاكرة طويلة المدى",
    results: "النتائج",
  },
};

export const gameCopy = {
  appTitle: {
    en: "Brainora ADtect",
    ar: "Brainora ADtect",
  },
  topBar: {
    id: { en: "ID", ar: "المعرف" },
    stage: { en: "Stage", ar: "المرحلة" },
    mute: { en: "Mute", ar: "كتم" },
    unmute: { en: "Unmute", ar: "تشغيل الصوت" },
  },
  onboarding: {
    title: { en: "Welcome to Brainora ADtect", ar: "مرحبًا بك في Brainora ADtect" },
    description: {
      en: "Brainora ADtect is an interactive cognitive assessment that evaluates your memory, sequencing, and problem-solving abilities through engaging dance movement videos, puzzles, and a clinically-validated questionnaire. The assessment takes about 15 minutes and is designed to be both fun and insightful.",
      ar: "Brainora ADtect هو تقييم إدراكي تفاعلي يقيّم ذاكرتك وقدرتك على التسلسل وحل المشكلات من خلال مقاطع فيديو رقص تفاعلية وألغاز واستبيان معتمد إكلينيكياً. يستغرق التقييم حوالي 15 دقيقة.",
    },
    playIntro: { en: "Play Intro Audio", ar: "تشغيل صوت المقدمة" },
    button: { en: "Start Assessment", ar: "ابدأ التقييم" },
  },
  stageIntro: {
    playAudio: { en: "Play Instructions", ar: "تشغيل التعليمات" },
    playing: { en: "Playing…", ar: "جارٍ التشغيل…" },
    paused: { en: "Paused", ar: "متوقف" },
  },
  learning: {
    stageTitle: { en: "Stage 1 – Learning Phase", ar: "المرحلة 1 – مرحلة التعلّم" },
    stageDescription: {
      en: "You will watch 4 different dance movement clips. Each clip will play 3 times so you can memorize the movement and its name. After each clip's 3 repetitions, you'll be tested on it immediately.",
      ar: "ستشاهد 4 مقاطع رقص مختلفة. سيتم تشغيل كل مقطع 3 مرات حتى تتمكن من حفظ الحركة واسمها. بعد كل 3 تكرارات ستُختبر فوراً.",
    },
    instructionsLabel: { en: "Instructions", ar: "التعليمات" },
    instructions: {
      en: "Watch each dancing video 3 times carefully — you will be tested on it right after.",
      ar: "شاهد كل فيديو رقص 3 مرات بعناية — ستُختبر عليه مباشرة بعد ذلك.",
    },
    nowLearning: { en: "Now learning:", ar: "تتعلم الآن:" },
    remember: { en: "Watch the movement and remember the label.", ar: "شاهد الحركة وتذكّر الاسم." },
    clipCounter: { en: "Clip", ar: "المقطع" },
    repetition: { en: "Repetition", ar: "التكرار" },
    playClip: { en: "Play Clip", ar: "تشغيل المقطع" },
    playAgain: { en: "Play Again", ar: "أعد التشغيل" },
    learnedTitle: { en: "All Clips Learned!", ar: "تمت مشاهدة جميع المقاطع!" },
    learnedDescription: {
      en: "You've watched all 4 movement clips and completed their immediate memory tests. Click Next to continue.",
      ar: "لقد شاهدت جميع المقاطع الأربعة وأكملت اختبارات الذاكرة الفورية. اضغط التالي للمتابعة.",
    },
    next: { en: "Next", ar: "التالي" },
  },
  shortTerm: {
    stageTitle: { en: "Short-Term Memory Test", ar: "اختبار الذاكرة قصيرة المدى" },
    stageDescription: {
      en: "Now identify the clip you just watched. Select the correct movement from the options below.",
      ar: "الآن حدد المقطع الذي شاهدته للتو. اختر الحركة الصحيحة من الخيارات أدناه.",
    },
    prompt: { en: "Which movement matches this name?", ar: "أي حركة تطابق هذا الاسم؟" },
    helper: { en: "Click the correct movement clip below.", ar: "اضغط على مقطع الحركة الصحيح بالأسفل." },
    nextQuestion: { en: "Next Question", ar: "السؤال التالي" },
    continue: { en: "Continue", ar: "متابعة" },
    question: { en: "Question", ar: "السؤال" },
    of: { en: "of", ar: "من" },
  },
  reordering: {
    stageTitle: { en: "Stage 3 – Reordering Task", ar: "المرحلة 3 – مهمة الترتيب" },
    stageDescription: {
      en: "The '6 8' clip has been divided into 6 segments. Put them in the correct chronological order.",
      ar: "تم تقسيم مقطع '6 8' إلى 6 أجزاء. رتبها بالترتيب الزمني الصحيح.",
    },
    title: { en: "Reordering Task", ar: "مهمة الترتيب" },
    description: {
      en: 'The "6 8" clip has been divided into 6 segments shown below. Select the option that shows the correct chronological order of these segments.',
      ar: 'تم تقسيم مقطع "6 8" إلى 6 أجزاء موضحة بالأسفل. اختر الخيار الذي يعرض الترتيب الزمني الصحيح لهذه الأجزاء.',
    },
    correct: { en: "✅ Correct! The right sequence is option G.", ar: "✅ صحيح! الترتيب الصحيح هو الخيار G." },
    incorrectPrefix: { en: "❌ Incorrect. The correct answer was G", ar: "❌ غير صحيح. الإجابة الصحيحة كانت G" },
    continue: { en: "Continue", ar: "متابعة" },
  },
  puzzle: {
    stageTitle: { en: "Stage 4 – Puzzle", ar: "المرحلة 4 – اللغز" },
    stageDescription: {
      en: "Navigate the 3×3 grid from START to the treasure chest. Collect the key first and avoid crabs!",
      ar: "تنقل في الشبكة 3×3 من البداية إلى صندوق الكنز. اجمع المفتاح أولاً وتجنب السرطانات!",
    },
    rules: { en: "Rules", ar: "القواعد" },
    ruleStart: { en: "• Start on the START tile", ar: "• ابدأ من خانة START" },
    ruleAdjacent: { en: "• Move to any adjacent tile (including diagonals)", ar: "• تحرك إلى أي خانة مجاورة بما في ذلك القطرية" },
    ruleNoRevisit: { en: "• No revisiting tiles", ar: "• ممنوع زيارة نفس الخانة مرة أخرى" },
    ruleSand: { en: "• Visit all sand tiles", ar: "• زر جميع خانات الرمل" },
    ruleCrabs: { en: "• Avoid crabs 🦀", ar: "• تجنب السرطانات 🦀" },
    ruleKey: { en: "• Collect the key before the chest", ar: "• اجمع المفتاح قبل الصندوق" },
    sandTiles: { en: "Sand tiles", ar: "خانات الرمل" },
    key: { en: "Key", ar: "المفتاح" },
    collected: { en: "✅ Collected", ar: "✅ تم جمعه" },
    notCollected: { en: "❌ Not collected", ar: "❌ لم يتم جمعه" },
    retry: { en: "Retry", ar: "إعادة المحاولة" },
    continue: { en: "Continue", ar: "متابعة" },
    status: {
      idle: { en: "Click the START tile to begin.", ar: "اضغط على خانة START للبدء." },
      playing: { en: "Navigate to the treasure chest!", ar: "اتجه إلى صندوق الكنز!" },
      success: { en: "🎉 Congratulations! Puzzle completed successfully!", ar: "🎉 رائع! تم حل اللغز بنجاح!" },
      fail_crab: { en: "🦀 You stepped on a crab. Puzzle failed.", ar: "🦀 لقد وقفت على سرطان. فشل اللغز." },
      fail_no_key: { en: "🔒 Chest is locked — you did not collect the key.", ar: "🔒 الصندوق مقفل — لم تجمع المفتاح." },
      fail_incomplete: { en: "⚠️ You haven't visited all sand tiles yet.", ar: "⚠️ لم تزر جميع خانات الرمل بعد." },
    },
  },
  longTerm: {
    stageTitle: { en: "Stage 5 – Long-Term Memory", ar: "المرحلة 5 – الذاكرة طويلة المدى" },
    stageDescription: {
      en: "Watch each clip and recall its name from earlier. This tests how well you retained the movement names.",
      ar: "شاهد كل مقطع وتذكر اسمه من وقت سابق. هذا يختبر مدى احتفاظك بأسماء الحركات.",
    },
    prompt: { en: "Watch the clip and select the correct label", ar: "شاهد المقطع واختر الاسم الصحيح" },
    nextQuestion: { en: "Next Question", ar: "السؤال التالي" },
    viewResults: { en: "View Results", ar: "عرض النتائج" },
    question: { en: "Question", ar: "السؤال" },
    of: { en: "of", ar: "من" },
  },
  results: {
    title: { en: "Assessment Complete", ar: "اكتمل التقييم" },
    player: { en: "Player", ar: "اللاعب" },
    compositeScore: { en: "Composite Score", ar: "الدرجة الإجمالية" },
    shortTerm: { en: "Short-Term Memory", ar: "الذاكرة قصيرة المدى" },
    longTerm: { en: "Long-Term Memory", ar: "الذاكرة طويلة المدى" },
    reordering: { en: "Reordering", ar: "الترتيب" },
    puzzle: { en: "Puzzle", ar: "اللغز" },
    correct: { en: "✅ Correct", ar: "✅ صحيح" },
    incorrect: { en: "❌ Incorrect", ar: "❌ غير صحيح" },
    solved: { en: "✅ Solved", ar: "✅ تم الحل" },
    failed: { en: "❌ Failed", ar: "❌ فشل" },
    answer: { en: "Answer", ar: "الإجابة" },
    avg: { en: "Avg", ar: "المتوسط" },
    secondsShort: { en: "s", ar: "ث" },
    savingResults: { en: "Saving results…", ar: "جارٍ حفظ النتائج…" },
    savedSuccess: { en: "Results saved!", ar: "تم حفظ النتائج!" },
    goToDashboard: { en: "Go to Dashboard", ar: "الذهاب إلى لوحة التحكم" },
  },
  questionnaire: {
    stageTitle: { en: "Alzheimer's Questionnaire (AQ©)", ar: "استبيان الزهايمر (AQ©)" },
    stageDescription: {
      en: "Answer each question with Yes or No. Score a 'Yes' only when there has been a decline compared to the previous level of functioning.",
      ar: "أجب على كل سؤال بنعم أو لا. أجب بـ 'نعم' فقط عند وجود تراجع مقارنة بالمستوى السابق.",
    },
    yes: { en: "Yes", ar: "نعم" },
    no: { en: "No", ar: "لا" },
    submit: { en: "Submit Questionnaire", ar: "إرسال الاستبيان" },
    resultTitle: { en: "Your AQ© Score", ar: "درجتك في استبيان AQ©" },
    interpretation: {
      normal: { en: "Within normal range (0–4).", ar: "ضمن المعدل الطبيعي (0–4)." },
      mild_cognitive_impairment: { en: "Suggests mild cognitive impairment (5–14).", ar: "يشير إلى ضعف إدراكي خفيف (5–14)." },
      dementia: { en: "Suggests dementia (15+).", ar: "يشير إلى الخرف (15+)." },
    },
    continue: { en: "Continue to Assessment", ar: "المتابعة إلى التقييم" },
    listenQuestions: { en: "Listen to Questions", ar: "استمع للأسئلة" },
  },
  auth: {
    login: { en: "Log In", ar: "تسجيل الدخول" },
    signup: { en: "Sign Up", ar: "إنشاء حساب" },
    email: { en: "Email", ar: "البريد الإلكتروني" },
    password: { en: "Password", ar: "كلمة المرور" },
    noAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
    hasAccount: { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
    logout: { en: "Log Out", ar: "تسجيل الخروج" },
    orContinueWith: { en: "Or continue with", ar: "أو تابع باستخدام" },
    googleSignIn: { en: "Sign in with Google", ar: "تسجيل الدخول بجوجل" },
  },
  dashboard: {
    title: { en: "Dashboard", ar: "لوحة التحكم" },
    startGame: { en: "Start New Assessment", ar: "بدء تقييم جديد" },
    viewProfile: { en: "View Profile & Scores", ar: "عرض الملف الشخصي والنتائج" },
    welcome: { en: "Welcome back!", ar: "مرحباً بعودتك!" },
  },
  profile: {
    title: { en: "My Profile", ar: "ملفي الشخصي" },
    gameHistory: { en: "Assessment Results", ar: "نتائج التقييم" },
    aqScore: { en: "AQ© Score", ar: "درجة AQ©" },
    noSessions: { en: "No sessions yet. Start an assessment!", ar: "لا توجد جلسات بعد. ابدأ تقييماً!" },
    date: { en: "Date", ar: "التاريخ" },
    score: { en: "Score", ar: "الدرجة" },
    back: { en: "Back", ar: "رجوع" },
    viewDetails: { en: "View Details", ar: "عرض التفاصيل" },
    sessionDetails: { en: "Session Details", ar: "تفاصيل الجلسة" },
    close: { en: "Close", ar: "إغلاق" },
    responses: { en: "Responses", ar: "الإجابات" },
    stage: { en: "Stage", ar: "المرحلة" },
    target: { en: "Target", ar: "الهدف" },
    selected: { en: "Selected", ar: "المختار" },
    correct: { en: "Correct", ar: "صحيح" },
    responseTime: { en: "Response Time", ar: "وقت الاستجابة" },
    name: { en: "Name", ar: "الاسم" },
    shortTerm: { en: "Short-term", ar: "ذاكرة قصيرة" },
    longTerm: { en: "Long-term", ar: "ذاكرة طويلة" },
    reordering: { en: "Reordering", ar: "ترتيب" },
    puzzle: { en: "Puzzle", ar: "لغز" },
    finalScore: { en: "Final Score", ar: "الدرجة النهائية" },
  },
  theme: {
    system: { en: "System", ar: "النظام" },
    light: { en: "Light", ar: "فاتح" },
    dark: { en: "Dark", ar: "داكن" },
  },
} as const;
